import type { RenderMarkdownOptions } from "@fleet-console/markdown/core";
import type { DiagramHydratorLabels } from "@fleet-console/markdown/mermaid";
import type { ConsoleLocale, Translate } from "@fleet-console/sdk/i18n";
import { createTranslator } from "@fleet-console/sdk/i18n/translate";

const scuttlebuttEn = {
  "chat.label.tori": "Aide Tori",
  "chat.label.bori": "Aide Bori",
  "chat.label.dori": "Aide Dori",
  "chat.tuck": "Tuck away",
  "chat.stayPut": "Stay put",
  "chat.stayPut.hint": "The aide stays where it is. Press again to release. (Space)",
  "chat.dock": "Put on the top bar",
  "chat.dock.hint": "Moves the aide to a glyph at the top right. Answers open beneath it.",
  "chat.undock": "Detach",
  "chat.undock.hint": "Returns the aide to the canvas — to its stay-put spot if it had one.",
  "chat.tuck.hint": "Closes this surface. The conversation stays with the aide.",
  "action.clear.hint": "Clears this aide's conversation.",
  "dock.groupAria": "Aides on the top bar",
  "dock.unreadAria": "{name} — new answer",
  "dock.dropHere": "Drop here",
  "chat.placeholder.tori": "Ask Tori anything…",
  "chat.placeholder.bori": "Ask Bori anything…",
  "chat.placeholder.dori": "Ask Dori anything…",
  "chat.send": "Send",
  "chat.greeting.tori": "Tori, on the flagship bridge. Questions or orders, Admiral — I search the web, and with Console use enabled, coordinate your Operations.",
  "chat.greeting.bori": "Bori here! Signals up! Questions or orders — with Console use enabled, I can put your Operations in motion!",
  "chat.greeting.dori": "Dori, just in from patrol. I check facts and report results. With Console use enabled, entrust your Operations to me as well.",
  "chat.thinking.tori": "Tori is looking into it…",
  "chat.thinking.bori": "Bori is running it down…",
  "chat.thinking.dori": "Dori is scouting it out…",
  "status.searching": "Searching…",
  "status.reading": "Reading a source…",
  "status.working": "Working…",
  "status.searchDone": "Searched the web",
  "status.readDone": "Read a source",
  "status.toolDone": "Done",
  "status.toolFailed": "A lookup failed",
  "error.session_unavailable": "The AI Gateway isn't ready yet. Try again in a moment.",
  "error.session_capacity": "Every aide is busy right now. Try again shortly.",
  "error.session_busy": "{name} is still answering. Wait, or stop the answer.",
  "error.session_not_found": "{name} stepped away for a moment. Ask again.",
  "error.stream_closed": "Lost the line to {name}. Ask again to reconnect.",
  "error.chat_error": "{name} couldn't finish that answer.",
  "error.forbidden": "This Console doesn't allow chat from here.",
  "error.generic": "Chat is unavailable right now.",
  "notice.rejoined": "{name} was away for a moment and is back on station.",
  "notice.cancelled": "Stopped.",
  "action.retry": "Try again",
  "action.stop": "Stop",
  "action.copy": "Copy answer",
  "action.copied": "Copied",
  "action.handoff": "Send to Quick Launch",
  "action.clear": "Clear chat",
  "sources.label": "Sources",
  "usage.line": "This answer: {tokens} tokens · {cost}",
  "usage.lineNoCost": "This answer: {tokens} tokens",
  "awaiting.label": "Waiting for you",
  "awaiting.open": "Open operation",
  "awaiting.manyCount": "{count} operations",
  "intro.title": "{name}, reporting for duty",
  "intro.body": "Click {name} or type @{name} in Quick Launch. Ask questions, or enable Console use in Experiments to entrust Operations to your aide. AI execution uses your configured account.",
  "intro.ok": "Understood",
  "settings.section.model": "Model and effort",
  "settings.section.modelHint": "Shared model and reasoning effort for all aides.",
  "settings.section.modelAria": "Aide model",
  "settings.section.effortAria": "Aide effort",
  "effort.low": "Low",
  "effort.medium": "Medium",
  "effort.high": "High",
  "bird.keyboardHint": "Arrow keys move {name}; Space toggles Stay put.",
  "arrival.done": "Finished",
  "arrival.open": "Open operation",
  "arrival.manyCount": "{count} operations",
  "departure.started": "Started",
  "departure.open": "Open operation",
  "departure.manyCount": "{count} operations",
  "bubble.dismiss": "Dismiss",
  "settings.section.title": "Quaker Aides",
  "settings.section.experimental": "Experimental",
  "settings.section.roster": "Aides on duty",
  "settings.helpTipAria": "Help — {title}",
  "settings.section.departure": "Announce when work starts",
  "settings.section.departureHint": "An aide speaks up as an operation begins.",
  "settings.section.departureToggle": "Announce",
  "settings.section.rosterHint": "Choose which aides appear on screen.",
  "settings.section.size": "Figure size",
  "settings.section.sizeHint": "Adjust each aide’s size on screen.",
  "settings.section.sizeAria": "{name} figure size",
  "settings.section.sizeDecrease": "Make {name} smaller",
  "settings.section.sizeIncrease": "Make {name} larger",
  "settings.section.sizeReset": "Reset {name} to the standard size",
  "settings.section.sizeResetShort": "Standard",
  "mention.category": "Aides",
  "mention.capability": "Web only",
  "mention.capabilityConsole": "Web + Console use",
  "mention.description": "{name} answers from web search only — no repository or file access.",
  "mention.descriptionConsole": "{name} searches the web, launches and directs Operations, checks results, and manages bounded automation. No direct file or shell access.",
  "answer.dismiss": "Dismiss",
  "answer.followUp": "Ask a follow-up",
  "markdown.copy": "Copy",
  "markdown.copyCodeAria": "Copy {language} code",
  "diagram.renderFailed": "Diagram render failed: {message}",
  "diagram.openExpandedAria": "Open diagram in expanded view",
  "diagram.lightboxTitle": "MANIFEST · DIAGRAM",
  "diagram.close": "Close",
  "diagram.closeExpandedAria": "Close expanded diagram",
  "diagram.zoomControlsAria": "Diagram zoom controls",
  "diagram.zoomOutAria": "Zoom out",
  "diagram.zoomInAria": "Zoom in",
  "diagram.fit": "Fit",
  "diagram.fitAria": "Fit diagram to viewport",
  "diagram.reset": "Reset",
  "diagram.resetAria": "Reset diagram zoom",
  "answer.working": "Looking it up…",
  "bird.tori": "Tori",
  "bird.bori": "Bori",
  "bird.dori": "Dori",
  "line.tori.1": "All ships, hold your course.",
  "line.tori.2": "Flagship reports all clear.",
  "line.tori.3": "Tori holding station.",
  "line.bori.1": "Signal received, loud and clear!",
  "line.bori.2": "Run up the flags!",
  "line.bori.3": "Courier Bori — dispatch coming through!",
  "line.dori.1": "Patrol reports nothing unusual.",
  "line.dori.2": "Dori entering the patrol route.",
  "line.dori.3": "Output streams are steady.",
} as const;

export type ScuttlebuttMessageKey = keyof typeof scuttlebuttEn;

const scuttlebuttKo: Record<ScuttlebuttMessageKey, string> = {
  "chat.label.tori": "토리 부관",
  "chat.label.bori": "보리 부관",
  "chat.label.dori": "도리 부관",
  "chat.tuck": "치워두기",
  "chat.stayPut": "제자리에 두기",
  "chat.stayPut.hint": "부관이 지금 자리에서 움직이지 않습니다. 다시 누르면 풀립니다. (Space)",
  "chat.dock": "상단 바에 두기",
  "chat.dock.hint": "부관을 상단 바 우측 글리프로 옮깁니다. 답은 글리프 아래에 섭니다.",
  "chat.undock": "떼어내기",
  "chat.undock.hint": "부관을 캔버스로 되돌립니다. 제자리에 두었던 자리면 그곳으로 갑니다.",
  "chat.tuck.hint": "이 표면을 닫습니다. 대화는 부관에게 남습니다.",
  "action.clear.hint": "이 부관과의 대화를 지웁니다.",
  "dock.groupAria": "상단 바의 부관",
  "dock.unreadAria": "{name} — 새 답",
  "dock.dropHere": "여기에 놓기",
  "chat.placeholder.tori": "토리에게 무엇이든 물어보세요…",
  "chat.placeholder.bori": "보리에게 무엇이든 물어보세요…",
  "chat.placeholder.dori": "도리에게 무엇이든 물어보세요…",
  "chat.send": "보내기",
  "chat.greeting.tori": "기함 함교의 토리입니다. 질문이든 지시든 말씀하십시오. 웹을 살피고, 콘솔 사용을 켜면 Operation 운영도 맡습니다.",
  "chat.greeting.bori": "보리! 신호 대기 중입니다! 질문도 지시도 주세요. 콘솔 사용을 켜면 Operation 출격부터 맡겠습니다!",
  "chat.greeting.dori": "초계에서 막 돌아온 도리입니다. 사실을 확인하고 결과를 보고합니다. 콘솔 사용을 켜면 Operation 운영도 맡겨 주십시오.",
  "chat.thinking.tori": "토리가 살펴보는 중…",
  "chat.thinking.bori": "보리가 신호를 받는 중…",
  "chat.thinking.dori": "도리가 정찰하는 중…",
  "status.searching": "검색하는 중…",
  "status.reading": "출처를 읽는 중…",
  "status.working": "처리하는 중…",
  "status.searchDone": "웹을 검색함",
  "status.readDone": "출처 하나를 읽음",
  "status.toolDone": "완료",
  "status.toolFailed": "조회에 실패함",
  "error.session_unavailable": "AI Gateway가 아직 준비되지 않았습니다. 잠시 뒤 다시 물어보세요.",
  "error.session_capacity": "지금은 부관이 모두 바쁩니다. 잠시 뒤 다시 물어보세요.",
  "error.session_busy": "{name}가 아직 답하는 중입니다. 기다리거나 멈추세요.",
  "error.session_not_found": "{name}가 잠시 자리를 비웠습니다. 다시 물어보세요.",
  "error.stream_closed": "{name}와의 연결이 끊겼습니다. 다시 물어보면 이어집니다.",
  "error.chat_error": "{name}가 답을 끝내지 못했습니다.",
  "error.forbidden": "이 Console은 여기서의 대화를 허용하지 않습니다.",
  "error.generic": "지금은 대화를 할 수 없습니다.",
  "notice.rejoined": "{name}가 잠시 자리를 비웠다가 돌아왔습니다.",
  "notice.cancelled": "멈췄습니다.",
  "action.retry": "다시 시도",
  "action.stop": "멈추기",
  "action.copy": "답 복사",
  "action.copied": "복사됨",
  "action.handoff": "Quick Launch로 보내기",
  "action.clear": "대화 지우기",
  "sources.label": "출처",
  "usage.line": "이번 답: 토큰 {tokens} · {cost}",
  "usage.lineNoCost": "이번 답: 토큰 {tokens}",
  "awaiting.label": "입력 대기",
  "awaiting.open": "Operation 열기",
  "awaiting.manyCount": "Operation {count}건",
  "intro.title": "{name}, 출근 보고",
  "intro.body": "{name}를 누르거나 Quick Launch에서 @{name}으로 부르세요. 질문에 답하고, 실험에서 콘솔 사용을 켜면 Operation도 맡습니다. AI 실행에는 설정한 계정의 사용량이 듭니다.",
  "intro.ok": "알겠습니다",
  "settings.section.model": "모델과 강도",
  "settings.section.modelHint": "모든 부관이 사용할 모델과 추론 강도입니다.",
  "settings.section.modelAria": "부관 모델",
  "settings.section.effortAria": "부관 강도",
  "effort.low": "낮음",
  "effort.medium": "보통",
  "effort.high": "높음",
  "bird.keyboardHint": "방향키로 {name}를 옮기고, Space로 제자리에 두기를 켜고 끕니다.",
  "arrival.done": "작업 완료",
  "arrival.open": "Operation 열기",
  "arrival.manyCount": "Operation {count}건",
  "departure.started": "작업 시작",
  "departure.open": "Operation 열기",
  "departure.manyCount": "Operation {count}건",
  "bubble.dismiss": "닫기",
  "settings.section.title": "퀘이커 부관단",
  "settings.section.experimental": "실험",
  "settings.section.roster": "출근 중인 부관",
  "settings.helpTipAria": "{title} 도움말",
  "settings.section.departure": "작업 시작을 알리기",
  "settings.section.departureHint": "Operation이 시작될 때 부관이 알립니다.",
  "settings.section.departureToggle": "알리기",
  "settings.section.rosterHint": "화면에 표시할 부관을 고릅니다.",
  "settings.section.size": "부관 크기",
  "settings.section.sizeHint": "화면에 표시되는 부관의 크기를 조절합니다.",
  "settings.section.sizeAria": "{name} 크기",
  "settings.section.sizeDecrease": "{name} 작게",
  "settings.section.sizeIncrease": "{name} 크게",
  "settings.section.sizeReset": "{name}를 기본 크기로 되돌리기",
  "settings.section.sizeResetShort": "기본값",
  "mention.category": "부관",
  "mention.capability": "웹 전용",
  "mention.capabilityConsole": "웹 + 콘솔 사용",
  "mention.description": "{name}은(는) 웹 검색으로만 답합니다 — 저장소와 파일에는 접근하지 않습니다.",
  "mention.descriptionConsole": "{name}은(는) 웹 검색과 함께 Operation 실행·지시·결과 확인·제한된 자동 운영을 맡습니다. 파일·셸을 직접 다루지는 않습니다.",
  "answer.dismiss": "닫기",
  "answer.followUp": "이어 묻기",
  "markdown.copy": "복사",
  "markdown.copyCodeAria": "{language} 코드 복사",
  "diagram.renderFailed": "다이어그램 렌더 실패: {message}",
  "diagram.openExpandedAria": "다이어그램을 확대 보기로 열기",
  "diagram.lightboxTitle": "MANIFEST · DIAGRAM",
  "diagram.close": "닫기",
  "diagram.closeExpandedAria": "확대된 다이어그램 닫기",
  "diagram.zoomControlsAria": "다이어그램 확대/축소 컨트롤",
  "diagram.zoomOutAria": "축소",
  "diagram.zoomInAria": "확대",
  "diagram.fit": "맞춤",
  "diagram.fitAria": "뷰포트에 다이어그램 맞추기",
  "diagram.reset": "초기화",
  "diagram.resetAria": "다이어그램 확대/축소 초기화",
  "answer.working": "찾아보는 중…",
  "bird.tori": "토리",
  "bird.bori": "보리",
  "bird.dori": "도리",
  "line.tori.1": "전 함대, 항로 유지.",
  "line.tori.2": "기함은 이상 무.",
  "line.tori.3": "토리, 현 위치 사수.",
  "line.bori.1": "신호 수신 양호!",
  "line.bori.2": "깃발 올려!",
  "line.bori.3": "보리 전령, 급보 있음!",
  "line.dori.1": "초계 이상 무!",
  "line.dori.2": "도리, 초계 항로 진입.",
  "line.dori.3": "캐리어 스트림 정상.",
};

const SCUTTLEBUTT_MESSAGES = {
  en: scuttlebuttEn,
  ko: scuttlebuttKo,
} as const;

const translators: Record<ConsoleLocale, Translate<ScuttlebuttMessageKey>> = {
  en: createTranslator(SCUTTLEBUTT_MESSAGES, "en"),
  ko: createTranslator(SCUTTLEBUTT_MESSAGES, "ko"),
};

export function getT(locale: ConsoleLocale | undefined): Translate<ScuttlebuttMessageKey> {
  return translators[locale ?? "en"];
}

/** Mermaid 하이드레이터의 라벨은 모듈 전역이라, 이 표면이 설치할 때마다 자기 로케일로 다시 채운다. */
export function diagramHydratorLabels(locale: ConsoleLocale | undefined): DiagramHydratorLabels {
  const t = getT(locale);
  return {
    renderFailed: (message) => t("diagram.renderFailed", { message }),
    openExpandedAria: t("diagram.openExpandedAria"),
    lightboxTitle: t("diagram.lightboxTitle"),
    close: t("diagram.close"),
    closeExpandedAria: t("diagram.closeExpandedAria"),
    zoomControlsAria: t("diagram.zoomControlsAria"),
    zoomOutAria: t("diagram.zoomOutAria"),
    zoomInAria: t("diagram.zoomInAria"),
    fit: t("diagram.fit"),
    fitAria: t("diagram.fitAria"),
    reset: t("diagram.reset"),
    resetAria: t("diagram.resetAria"),
  };
}

/** 렌더러가 코드 블록마다 심는 Copy 버튼의 글자·aria-label. 답이 한국어면 버튼도 한국어여야 한다. */
export function markdownRenderOptions(locale: ConsoleLocale | undefined): RenderMarkdownOptions {
  const t = getT(locale);
  return {
    copyLabel: t("markdown.copy"),
    copyAriaLabel: (language) => t("markdown.copyCodeAria", { language }),
  };
}
