import type { ConsoleLocale, Translate } from "@fleet-console/sdk/i18n";
import { createTranslator } from "@fleet-console/sdk/i18n/translate";

const scuttlebuttEn = {
  "chat.label.tori": "Aide Tori",
  "chat.label.bori": "Aide Bori",
  "chat.label.dori": "Aide Dori",
  "chat.tuck": "Tuck away",
  "chat.stayPut": "Stay put",
  "chat.placeholder.tori": "Ask Tori anything…",
  "chat.placeholder.bori": "Ask Bori anything…",
  "chat.placeholder.dori": "Ask Dori anything…",
  "chat.send": "Send",
  "chat.greeting.tori": "Tori, on the flagship bridge. Ask anything that needs no workspace — including why the sea is salty. I search the web and never touch your files.",
  "chat.greeting.bori": "Bori here! Signals up! Throw me anything quick — I search the web, I never touch your files!",
  "chat.greeting.dori": "Dori, just in from patrol. Hand me anything worth checking — I search the web and never touch your files.",
  "chat.thinking.tori": "Tori is looking into it…",
  "chat.thinking.bori": "Bori is running it down…",
  "chat.thinking.dori": "Dori is scouting it out…",
  "status.searching": "Searching…",
  "status.reading": "Reading a source…",
  "status.working": "Working…",
  "arrival.done": "Finished",
  "arrival.open": "Open operation",
  "arrival.manyCount": "{count} operations",
  "departure.started": "Started",
  "departure.open": "Open operation",
  "departure.manyCount": "{count} operations",
  "bubble.dismiss": "Dismiss",
  "settings.section.title": "Quaker Aides",
  "settings.section.experimental": "Experimental",
  "settings.section.roster": "Aides on duty",
  "settings.section.departure": "Announce when work starts",
  "settings.section.departureHint": "An aide speaks up as an operation begins.",
  "settings.section.departureToggle": "Announce",
  "settings.section.rosterHint": "Each aide keeps their own chat.",
  "settings.section.size": "Figure size",
  "settings.section.sizeHint": "Set how much of the console each aide takes up. Smaller aides cover less of your work.",
  "settings.section.sizeAria": "{name} figure size",
  "settings.section.sizeDecrease": "Make {name} smaller",
  "settings.section.sizeIncrease": "Make {name} larger",
  "settings.section.sizeReset": "Reset {name} to the standard size",
  "settings.section.sizeResetShort": "Standard",
  "mention.category": "Aides",
  "mention.capability": "Web only",
  "mention.description": "{name} answers from web search only — no repository or file access.",
  "answer.dismiss": "Dismiss",
  "answer.expand": "Open the full answer",
  "answer.working": "Looking it up…",
  "bird.tori": "Tori",
  "bird.bori": "Bori",
  "bird.dori": "Dori",
  "line.tori.1": "All ships, hold your course.",
  "line.tori.2": "Flagship reports all clear.",
  "line.tori.3": "Tori holding station.",
  "line.bori.1": "Signal received, loud and clear!",
  "line.bori.2": "Run up the flags!",
  "line.bori.3": "Courier Bori — dispatch coming through!",
  "line.dori.1": "Patrol reports nothing unusual.",
  "line.dori.2": "Dori entering the patrol route.",
  "line.dori.3": "Output streams are steady.",
} as const;

export type ScuttlebuttMessageKey = keyof typeof scuttlebuttEn;

const scuttlebuttKo: Record<ScuttlebuttMessageKey, string> = {
  "chat.label.tori": "토리 부관",
  "chat.label.bori": "보리 부관",
  "chat.label.dori": "도리 부관",
  "chat.tuck": "치워두기",
  "chat.stayPut": "제자리에 두기",
  "chat.placeholder.tori": "토리에게 무엇이든 물어보세요…",
  "chat.placeholder.bori": "보리에게 무엇이든 물어보세요…",
  "chat.placeholder.dori": "도리에게 무엇이든 물어보세요…",
  "chat.send": "보내기",
  "chat.greeting.tori": "기함 함교의 토리입니다. 작업 공간이 필요 없는 일이라면 무엇이든 — 바다가 왜 짠지까지도 — 물어보십시오. 웹은 찾아보지만 파일은 건드리지 않습니다.",
  "chat.greeting.bori": "보리! 신호 대기 중입니다! 빠른 질문이면 뭐든 던지세요. 웹은 뒤지고, 파일은 안 건드립니다!",
  "chat.greeting.dori": "초계에서 막 돌아온 도리입니다. 확인이 필요한 것이 있으면 맡겨 주십시오. 웹은 살피되 파일에는 손대지 않습니다.",
  "chat.thinking.tori": "토리가 살펴보는 중…",
  "chat.thinking.bori": "보리가 신호를 받는 중…",
  "chat.thinking.dori": "도리가 정찰하는 중…",
  "status.searching": "검색하는 중…",
  "status.reading": "출처를 읽는 중…",
  "status.working": "처리하는 중…",
  "arrival.done": "작업 완료",
  "arrival.open": "Operation 열기",
  "arrival.manyCount": "Operation {count}건",
  "departure.started": "작업 시작",
  "departure.open": "Operation 열기",
  "departure.manyCount": "Operation {count}건",
  "bubble.dismiss": "닫기",
  "settings.section.title": "퀘이커 부관단",
  "settings.section.experimental": "실험 기능",
  "settings.section.roster": "출근 중인 부관",
  "settings.section.departure": "작업 시작을 알리기",
  "settings.section.departureHint": "Operation이 시작될 때 부관이 알립니다.",
  "settings.section.departureToggle": "알리기",
  "settings.section.rosterHint": "부관마다 대화가 따로 유지됩니다.",
  "settings.section.size": "부관 크기",
  "settings.section.sizeHint": "부관이 화면을 얼마나 차지할지 정합니다. 작을수록 작업 화면을 덜 가립니다.",
  "settings.section.sizeAria": "{name} 크기",
  "settings.section.sizeDecrease": "{name} 작게",
  "settings.section.sizeIncrease": "{name} 크게",
  "settings.section.sizeReset": "{name}를 기본 크기로 되돌리기",
  "settings.section.sizeResetShort": "기본값",
  "mention.category": "부관",
  "mention.capability": "웹 전용",
  "mention.description": "{name}은(는) 웹 검색으로만 답합니다 — 저장소와 파일에는 접근하지 않습니다.",
  "answer.dismiss": "닫기",
  "answer.expand": "전문 보기",
  "answer.working": "찾아보는 중…",
  "bird.tori": "토리",
  "bird.bori": "보리",
  "bird.dori": "도리",
  "line.tori.1": "전 함대, 항로 유지.",
  "line.tori.2": "기함은 이상 무.",
  "line.tori.3": "토리, 현 위치 사수.",
  "line.bori.1": "신호 수신 양호!",
  "line.bori.2": "깃발 올려!",
  "line.bori.3": "보리 전령, 급보 있음!",
  "line.dori.1": "초계 이상 무!",
  "line.dori.2": "도리, 초계 항로 진입.",
  "line.dori.3": "캐리어 스트림 정상.",
};

const SCUTTLEBUTT_MESSAGES = {
  en: scuttlebuttEn,
  ko: scuttlebuttKo,
} as const;

const translators: Record<ConsoleLocale, Translate<ScuttlebuttMessageKey>> = {
  en: createTranslator(SCUTTLEBUTT_MESSAGES, "en"),
  ko: createTranslator(SCUTTLEBUTT_MESSAGES, "ko"),
};

export function getT(locale: ConsoleLocale | undefined): Translate<ScuttlebuttMessageKey> {
  return translators[locale ?? "en"];
}
