import type { ConsoleLocale, Translate } from "@fleet-console/sdk/i18n";
import { createTranslator } from "@fleet-console/sdk/i18n/translate";

const scuttlebuttEn = {
  "chat.label.tori": "Aide Tori",
  "chat.label.bori": "Aide Bori",
  "chat.label.dori": "Aide Dori",
  "chat.tuck": "Tuck away",
  "chat.stayPut": "Stay put",
  "chat.placeholder.tori": "Ask Tori anything…",
  "chat.placeholder.bori": "Ask Bori anything…",
  "chat.placeholder.dori": "Ask Dori anything…",
  "chat.send": "Send",
  "chat.greeting.tori": "Tori, on the flagship bridge. Ask anything that needs no workspace — including why the sea is salty. I search the web and never touch your files.",
  "chat.greeting.bori": "Bori here! Signals up! Throw me anything quick — I search the web, I never touch your files!",
  "chat.greeting.dori": "Dori, just in from patrol. Hand me anything worth checking — I search the web and never touch your files.",
  "chat.thinking.tori": "Tori is looking into it…",
  "chat.thinking.bori": "Bori is running it down…",
  "chat.thinking.dori": "Dori is scouting it out…",
  "status.searching": "Searching…",
  "status.reading": "Reading a source…",
  "status.working": "Working…",
  "status.searchDone": "Searched the web",
  "status.readDone": "Read a source",
  "status.toolDone": "Done",
  "status.toolFailed": "A lookup failed",
  "error.session_unavailable": "The AI Gateway isn't ready yet. Try again in a moment.",
  "error.session_capacity": "Every aide is busy right now. Try again shortly.",
  "error.session_busy": "{name} is still answering. Wait, or stop the answer.",
  "error.session_not_found": "{name} stepped away for a moment. Ask again.",
  "error.stream_closed": "Lost the line to {name}. Ask again to reconnect.",
  "error.chat_error": "{name} couldn't finish that answer.",
  "error.forbidden": "This Console doesn't allow chat from here.",
  "error.generic": "Chat is unavailable right now.",
  "notice.rejoined": "{name} was away for a moment and is back on station.",
  "notice.cancelled": "Stopped.",
  "action.retry": "Try again",
  "action.stop": "Stop",
  "action.copy": "Copy answer",
  "action.copied": "Copied",
  "action.handoff": "Send to Quick Launch",
  "action.clear": "Clear chat",
  "sources.label": "Sources",
  "usage.line": "This answer: {tokens} tokens · {cost}",
  "usage.lineNoCost": "This answer: {tokens} tokens",
  "awaiting.label": "Waiting for you",
  "awaiting.open": "Open operation",
  "awaiting.manyCount": "{count} operations",
  "intro.title": "{name}, reporting for duty",
  "intro.body": "Ask quick questions here — click {name} or type @{name} in Quick Launch. Answers come from web search only; your files are never touched. Each answer runs on your Claude account.",
  "intro.ok": "Understood",
  "settings.section.model": "Model and effort",
  "settings.section.modelHint": "Every aide answers on this model at this effort. Claude aliases are always listed; models enabled in AI Gateway are added by their plugin. A change applies from the next question.",
  "settings.section.modelAria": "Aide model",
  "settings.section.effortAria": "Aide effort",
  "effort.low": "Low",
  "effort.medium": "Medium",
  "effort.high": "High",
  "bird.keyboardHint": "Arrow keys move {name}; Space toggles Stay put.",
  "arrival.done": "Finished",
  "arrival.open": "Open operation",
  "arrival.manyCount": "{count} operations",
  "departure.started": "Started",
  "departure.open": "Open operation",
  "departure.manyCount": "{count} operations",
  "bubble.dismiss": "Dismiss",
  "settings.section.title": "Quaker Aides",
  "settings.section.experimental": "Experimental",
  "settings.section.roster": "Aides on duty",
  "settings.helpTipAria": "Help — {title}",
  "settings.section.departure": "Announce when work starts",
  "settings.section.departureHint": "An aide speaks up as an operation begins.",
  "settings.section.departureToggle": "Announce",
  "settings.section.consoleRead": "Read the Console",
  "settings.section.consoleReadHint": "Aides can read Operation titles, status, and Wiki entries and answer questions about them. Read only, on their usual model. Off, aides keep to web search.",
  "settings.section.consoleReadToggle": "Console reading",
  "settings.section.rosterHint": "Each aide keeps their own chat. Ctrl/⌘+Shift+Q opens the last aide you spoke with.",
  "settings.section.size": "Figure size",
  "settings.section.sizeHint": "Set how much of the console each aide takes up. Smaller aides cover less of your work.",
  "settings.section.sizeAria": "{name} figure size",
  "settings.section.sizeDecrease": "Make {name} smaller",
  "settings.section.sizeIncrease": "Make {name} larger",
  "settings.section.sizeReset": "Reset {name} to the standard size",
  "settings.section.sizeResetShort": "Standard",
  "mention.category": "Aides",
  "mention.capability": "Web only",
  "mention.capabilityConsole": "Web + Console (read)",
  "mention.description": "{name} answers from web search only — no repository or file access.",
  "mention.descriptionConsole": "{name} answers from web search and can read Operation titles, status, and Wiki entries — no repository or file access.",
  "answer.dismiss": "Dismiss",
  "answer.expand": "Open the full answer",
  "answer.working": "Looking it up…",
  "bird.tori": "Tori",
  "bird.bori": "Bori",
  "bird.dori": "Dori",
  "line.tori.1": "All ships, hold your course.",
  "line.tori.2": "Flagship reports all clear.",
  "line.tori.3": "Tori holding station.",
  "line.bori.1": "Signal received, loud and clear!",
  "line.bori.2": "Run up the flags!",
  "line.bori.3": "Courier Bori — dispatch coming through!",
  "line.dori.1": "Patrol reports nothing unusual.",
  "line.dori.2": "Dori entering the patrol route.",
  "line.dori.3": "Output streams are steady.",
} as const;

export type ScuttlebuttMessageKey = keyof typeof scuttlebuttEn;

const scuttlebuttKo: Record<ScuttlebuttMessageKey, string> = {
  "chat.label.tori": "토리 부관",
  "chat.label.bori": "보리 부관",
  "chat.label.dori": "도리 부관",
  "chat.tuck": "치워두기",
  "chat.stayPut": "제자리에 두기",
  "chat.placeholder.tori": "토리에게 무엇이든 물어보세요…",
  "chat.placeholder.bori": "보리에게 무엇이든 물어보세요…",
  "chat.placeholder.dori": "도리에게 무엇이든 물어보세요…",
  "chat.send": "보내기",
  "chat.greeting.tori": "기함 함교의 토리입니다. 작업 공간이 필요 없는 일이라면 무엇이든 — 바다가 왜 짠지까지도 — 물어보십시오. 웹은 찾아보지만 파일은 건드리지 않습니다.",
  "chat.greeting.bori": "보리! 신호 대기 중입니다! 빠른 질문이면 뭐든 던지세요. 웹은 뒤지고, 파일은 안 건드립니다!",
  "chat.greeting.dori": "초계에서 막 돌아온 도리입니다. 확인이 필요한 것이 있으면 맡겨 주십시오. 웹은 살피되 파일에는 손대지 않습니다.",
  "chat.thinking.tori": "토리가 살펴보는 중…",
  "chat.thinking.bori": "보리가 신호를 받는 중…",
  "chat.thinking.dori": "도리가 정찰하는 중…",
  "status.searching": "검색하는 중…",
  "status.reading": "출처를 읽는 중…",
  "status.working": "처리하는 중…",
  "status.searchDone": "웹을 검색함",
  "status.readDone": "출처 하나를 읽음",
  "status.toolDone": "완료",
  "status.toolFailed": "조회에 실패함",
  "error.session_unavailable": "AI Gateway가 아직 준비되지 않았습니다. 잠시 뒤 다시 물어보세요.",
  "error.session_capacity": "지금은 부관이 모두 바쁩니다. 잠시 뒤 다시 물어보세요.",
  "error.session_busy": "{name}가 아직 답하는 중입니다. 기다리거나 멈추세요.",
  "error.session_not_found": "{name}가 잠시 자리를 비웠습니다. 다시 물어보세요.",
  "error.stream_closed": "{name}와의 연결이 끊겼습니다. 다시 물어보면 이어집니다.",
  "error.chat_error": "{name}가 답을 끝내지 못했습니다.",
  "error.forbidden": "이 Console은 여기서의 대화를 허용하지 않습니다.",
  "error.generic": "지금은 대화를 할 수 없습니다.",
  "notice.rejoined": "{name}가 잠시 자리를 비웠다가 돌아왔습니다.",
  "notice.cancelled": "멈췄습니다.",
  "action.retry": "다시 시도",
  "action.stop": "멈추기",
  "action.copy": "답 복사",
  "action.copied": "복사됨",
  "action.handoff": "Quick Launch로 보내기",
  "action.clear": "대화 지우기",
  "sources.label": "출처",
  "usage.line": "이번 답: 토큰 {tokens} · {cost}",
  "usage.lineNoCost": "이번 답: 토큰 {tokens}",
  "awaiting.label": "입력 대기",
  "awaiting.open": "Operation 열기",
  "awaiting.manyCount": "Operation {count}건",
  "intro.title": "{name}, 출근 보고",
  "intro.body": "빠른 질문은 여기서. {name}를 누르거나 Quick Launch에서 @{name}으로 물어보세요. 답은 웹 검색으로만 찾고 파일은 건드리지 않습니다. 답마다 Claude 계정의 사용량이 듭니다.",
  "intro.ok": "알겠습니다",
  "settings.section.model": "모델과 강도",
  "settings.section.modelHint": "모든 부관이 이 모델과 강도로 답합니다. Claude 별칭은 항상 있고, AI Gateway에서 켠 모델은 그 플러그인이 보탭니다. 바꾸면 다음 질문부터 적용됩니다.",
  "settings.section.modelAria": "부관 모델",
  "settings.section.effortAria": "부관 강도",
  "effort.low": "낮음",
  "effort.medium": "보통",
  "effort.high": "높음",
  "bird.keyboardHint": "방향키로 {name}를 옮기고, Space로 제자리에 두기를 켜고 끕니다.",
  "arrival.done": "작업 완료",
  "arrival.open": "Operation 열기",
  "arrival.manyCount": "Operation {count}건",
  "departure.started": "작업 시작",
  "departure.open": "Operation 열기",
  "departure.manyCount": "Operation {count}건",
  "bubble.dismiss": "닫기",
  "settings.section.title": "퀘이커 부관단",
  "settings.section.experimental": "실험 기능",
  "settings.section.roster": "출근 중인 부관",
  "settings.helpTipAria": "{title} 도움말",
  "settings.section.departure": "작업 시작을 알리기",
  "settings.section.departureHint": "Operation이 시작될 때 부관이 알립니다.",
  "settings.section.departureToggle": "알리기",
  "settings.section.consoleRead": "Console 읽기",
  "settings.section.consoleReadHint": "부관이 Operation 제목·상태와 Wiki 항목을 읽고 그에 대해 답합니다. 평소 모델 그대로, 읽기 전용입니다. 끄면 부관은 웹 검색만 합니다.",
  "settings.section.consoleReadToggle": "Console 읽기",
  "settings.section.rosterHint": "부관마다 대화가 따로 유지됩니다. Ctrl/⌘+Shift+Q로 마지막에 말을 건 부관을 엽니다.",
  "settings.section.size": "부관 크기",
  "settings.section.sizeHint": "부관이 화면을 얼마나 차지할지 정합니다. 작을수록 작업 화면을 덜 가립니다.",
  "settings.section.sizeAria": "{name} 크기",
  "settings.section.sizeDecrease": "{name} 작게",
  "settings.section.sizeIncrease": "{name} 크게",
  "settings.section.sizeReset": "{name}를 기본 크기로 되돌리기",
  "settings.section.sizeResetShort": "기본값",
  "mention.category": "부관",
  "mention.capability": "웹 전용",
  "mention.capabilityConsole": "웹 + Console 읽기",
  "mention.description": "{name}은(는) 웹 검색으로만 답합니다 — 저장소와 파일에는 접근하지 않습니다.",
  "mention.descriptionConsole": "{name}은(는) 웹 검색과 함께 Operation 제목·상태·Wiki 항목을 읽고 답합니다 — 저장소와 파일에는 접근하지 않습니다.",
  "answer.dismiss": "닫기",
  "answer.expand": "전문 보기",
  "answer.working": "찾아보는 중…",
  "bird.tori": "토리",
  "bird.bori": "보리",
  "bird.dori": "도리",
  "line.tori.1": "전 함대, 항로 유지.",
  "line.tori.2": "기함은 이상 무.",
  "line.tori.3": "토리, 현 위치 사수.",
  "line.bori.1": "신호 수신 양호!",
  "line.bori.2": "깃발 올려!",
  "line.bori.3": "보리 전령, 급보 있음!",
  "line.dori.1": "초계 이상 무!",
  "line.dori.2": "도리, 초계 항로 진입.",
  "line.dori.3": "캐리어 스트림 정상.",
};

const SCUTTLEBUTT_MESSAGES = {
  en: scuttlebuttEn,
  ko: scuttlebuttKo,
} as const;

const translators: Record<ConsoleLocale, Translate<ScuttlebuttMessageKey>> = {
  en: createTranslator(SCUTTLEBUTT_MESSAGES, "en"),
  ko: createTranslator(SCUTTLEBUTT_MESSAGES, "ko"),
};

export function getT(locale: ConsoleLocale | undefined): Translate<ScuttlebuttMessageKey> {
  return translators[locale ?? "en"];
}
